apiVersion: apps/v1
kind: Deployment
metadata:
  name: testing-deployment
  labels:
    app: testing-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: testing-server
  template:
    metadata:
      labels:
        app: testing-server
    spec:
      containers:
      - name: http-server
        image: nginx:latest
        ports:
        - containerPort: 80
